<!DOCTYPE html>
<html lang="zh">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>动态数据显示</title>
    <script src="https://cdn.jsdelivr.net/npm/echarts/dist/echarts.min.js"></script>
</head>
<body>
    <div id="main" style="width: 420px; height: 250px; "></div>
    <script type="text/javascript">
        "object" != typeof ue || "object" != typeof ue.interface ? ("object" != typeof ue && (ue = {}),
            ue.interface = {}, ue.interface.broadcast = function (e, t) {
                if ("string" == typeof e) {
                    var o = [e, ""]; void 0 !== t && (o[1] = t); var n = encodeURIComponent(JSON.stringify(o));
                    "object" == typeof history && "function" == typeof history.pushState ? (history.pushState(
                        {}, "", "#" + n), history.pushState({}, "", "#" + encodeURIComponent("[]"))) :
                        (document.location.hash = n, document.location.hash = encodeURIComponent("[]"))
                }
            }) :
            function (e) {
                ue.interface = {}, ue.interface.broadcast = function (t, o) {
                    "string" == typeof t && (void 0 !== o ? e.broadcast(t, JSON.stringify(o)) :
                        e.broadcast(t, ""))
                }
            }(ue.interface), ue5 = ue.interface.broadcast;
            //WEB UI InitialEvent https://github.com/tracerinteractive/UnrealEngine/releases
        var myChart = echarts.init(document.getElementById('main'));
        const option = {
            title: {
                text: '降雨量(mm)',
                left: '6px',
                top: '5px',
                textStyle: {
                    fontSize: 12,
                    color: '#ffffff'
                }
            },
            grid: {
                left: 30,
                right: 20,
                top: 40,
                bottom: 20,
                containLabel: false
            },
            tooltip: {
                trigger: 'axis',
                textStyle: {
                    color: "black",
                },
                axisPointer: {
                    type: 'shadow'
                }
            },
            xAxis: {
                data: ['08:00', '10:00', '12:00', '14:00', '16:00', '18:00', '20:00', '22:00', '00:00', '02:00'],
                axisLabel: {
                    fontSize: 10,
                    color: '#FFFFFF'
                },
                axisLine: {
                    lineStyle: {
                        color: '#FFFFFF'
                    }
                }
            },
            yAxis: {
                min: 0,
                max: 120,
                splitLine: {
                    show: true,
                    lineStyle: {
                        type: 'dotted',
                        color: 'rgb(100, 100, 100)'
                    }
                },
                axisLabel: {
                    color: '#FFFFFF'
                },
                axisLine: {
                    lineStyle: {
                        color: '#FFFFFF'
                    }
                }
            },
            legend: {
                data: ['雨量', '累计雨量'],
                textStyle: {
                    color: "white",
                },
                right: 10,
            },
            series: [{
                name: '雨量',
                type: 'bar',
                barWidth: '20%',
                data: [60, 42, 38, 85, 70, 88, 111, 38, 46, 40],
                itemStyle: {
                    barBorderRadius: [50, 50, 0, 0],
                    color: new echarts.graphic.LinearGradient(
                        0, 0, 0, 1,
                        [
                            { offset: 0, color: 'rgb(165,225,226)' },
                            { offset: 1, color: '#1a7572' }
                        ]
                    )
                },
                label: {
                    show: true,
                    position: 'top',
                    color: 'rgb(195,244,255)'
                }
            }, {
                name: '累计雨量',
                type: 'line',
                data: [20, 30, 40, 50, 60, 70, 80, 90, 100, 110],
                smooth: false,
                symbol: 'none',
                color: "#FFD700",
                lineStyle: {
                    width: 2,
                    color: '#FFD700'
                }
            }]
        };

        myChart.setOption(option);
        ue.interface.ue2jss = function(ueData) {
            var jsonobj = JSON.parse(ueData);
            myChart.setOption(jsonobj);
            ue5("js2ue", "knjw");
        };
        // Receive Message From UE
        setInterval(function () {
            var firstDataValue = myChart.getOption().series[0].data[0];
            console.log('系列中的第一个数据值：', firstDataValue);

            // 假设你想将这个值发送到 UE5
            ue5("js2ue", { '系列中的第一个数据值：': firstDataValue });
            var rainData = option.series[0].data.map(function (datum) {
                var change = Math.floor(Math.random() * 21) - 10; // +-10的变化
                return Math.max(0, Math.min(120, datum + change));
            });
            var cumulativeData = option.series[1].data.map(function (datum, index) {
                if (index === 0) return datum; // 保持第一个数据点固定
                var change = Math.floor(Math.random() * 21) - 10;
                return Math.max(0, Math.min(120, datum + change));
            });
            myChart.setOption({
                series: [{
                    name: '雨量',
                    data: rainData
                }, {
                    name: '累计雨量',
                    data: cumulativeData
                }]
            });
        }, 2000); // 每两秒更新一次
    </script>
</body>
</html>
